#!/bin/csh -f
# $Id: chomkdir,v 1.2 1999/03/18 18:31:00 tominaga Exp $

# chomkdir - make a new cho directory, or normal directory cho directory

set dir="$1"
if ("$dir"x == x) then
    echo "usage: chomkdir dir"
    exit 1
else if ($dir == .) then
    set dirinfo=(`chodirinfo`)
    if ("$dirinfo[1]" == .) then
	echo 'cwd is not a cho-directory'
	exit 5
    else
	set dir="$dirinfo[1]"
	# continue to make $dir a cho-directory
    endif
endif
cd $CHOHOME
if (-d $dir) then
    if (-f $dir/.chocreated) then
	echo "cho-directory $dir already exists."
	exit 2
    else
	echo -n "make $dir be a cho-directory? (y/n) [n]"
	if ("$<"x !~ [Yy]*) then
	    echo "nothing done."
	    exit 3
	else
	    ;
	endif
    endif
else if (-f $dir) then
    echo "$dir exists and is not a directory."
    exit 4
else
    # $dir not exists
    mkdir $dir
endif
# make $dir be a cho-directory
if ($status == 0) then
    set today=`chotoday`
    echo $today > $dir/.chocreated
    echo $today > $dir/.choused
    echo "$dir" >> $dir/.chowhat
    echo "$dir" >> $dir/.chowhat.alt
    echo "$dir" >> $dir/.chokeys
    if (-f .chodirs) then
      mv .chodirs .chodirs.bak
      set noclobber
      (echo $dir; cat .chodirs.bak) > .chodirs
    else
      # no .chodirs; maybe first time to use
      echo $dir > .chodirs
    endif
    exit 0
else
    exit $status
fi
