#!/bin/csh -f
# $Id: chormap,v 1.1.1.2 1999/03/18 17:13:24 tominaga Exp $

# chormap - maps cho directory name to its tag

set dir=$1
set tags=(a b c d e f g h i j k l m n o p q r s t u v w x y z)
set dol='$'
set ns=(`egrep -n "^${dir}${dol}" $CHOHOME/.chodirs | sed 's/:.*//'`)
if ($#ns == 0) then
    exit 1
endif
foreach n ($ns)
    if ($n <= $#tags) then
	echo $tags[$n]
    else
	echo " "
    endif
end
exit 0
